/**
 * business-logic.canvas.tsx — generated by `subnet canvas business-logic`.
 *
 * Domain rules, invariants, entities extracted by the BusinessLogic Agent,
 * grouped by concept.
 */
import React from 'react';

interface BizFact {
  id: string;
  kind: string; // business_rule | entity | constraint | pattern
  title: string;
  summary?: string;
  evidence?: string;
  confidence: number;
}

interface BizGroup {
  conceptId: string;
  conceptName: string;
  conceptSummary?: string;
  facts: BizFact[];
}

const DATA: BizGroup[] = (globalThis as any).__SUBNET_BIZ_DATA__ ?? [];

const KIND_LABEL: Record<string, string> = {
  business_rule: 'Rule',
  entity: 'Entity',
  constraint: 'Constraint',
  pattern: 'Pattern',
};

export default function BusinessLogicCanvas() {
  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', padding: 16 }}>
      <h2 style={{ marginTop: 0 }}>Business logic</h2>
      {DATA.length === 0 && (
        <div style={{ opacity: 0.6 }}>
          No business-logic facts yet. The BusinessLogic Agent runs on windows
          whose triage domain is "business_logic" or "architecture".
        </div>
      )}
      <div style={{ display: 'grid', gap: 16 }}>
        {DATA.map((g) => (
          <section key={g.conceptId} style={{ border: '1px solid #2a2a2a', borderRadius: 6, padding: 12 }}>
            <header>
              <h3 style={{ margin: '0 0 4px 0' }}>{g.conceptName}</h3>
              {g.conceptSummary && (
                <div style={{ opacity: 0.85, marginBottom: 8 }}>{g.conceptSummary}</div>
              )}
            </header>
            <ul style={{ paddingLeft: 18, margin: 0 }}>
              {g.facts.map((f) => (
                <li key={f.id} style={{ marginBottom: 8 }}>
                  <span style={{
                    fontSize: 11, padding: '1px 6px', borderRadius: 4,
                    border: '1px solid #444', marginRight: 6, opacity: 0.85,
                  }}>{KIND_LABEL[f.kind] ?? f.kind}</span>
                  <strong>{f.title}</strong>
                  {f.summary && <div style={{ opacity: 0.85, marginTop: 2 }}>{f.summary}</div>}
                  {f.evidence && (
                    <blockquote style={{
                      margin: '6px 0 0 0', paddingLeft: 10,
                      borderLeft: '2px solid #444', opacity: 0.65,
                      fontFamily: 'ui-monospace, monospace', fontSize: 12,
                    }}>{f.evidence}</blockquote>
                  )}
                </li>
              ))}
            </ul>
          </section>
        ))}
      </div>
    </div>
  );
}
