/**
 * cross-project-bridge.canvas.tsx — generated by `subnet canvas cross-project-bridge`.
 *
 * Shows this project's concepts side-by-side with related concepts in other
 * projects. Each link carries the agent-assigned relation kind and score.
 */
import React, { useMemo, useState } from 'react';

interface CrossLink {
  relation: string;
  score: number;
  otherProject: string;
  otherName: string;
  otherSummary?: string;
}

interface LocalConcept {
  id: string;
  name: string;
  summary?: string;
  domain?: string;
  links: CrossLink[];
}

const DATA: LocalConcept[] = (globalThis as any).__SUBNET_BRIDGE_DATA__ ?? [];

const REL_COLORS: Record<string, string> = {
  same_as: '#5dd39e',
  variant_of: '#5ea0ef',
  supersedes: '#c98be0',
  contradicts: '#e0656e',
};

export default function CrossProjectBridgeCanvas() {
  const [project, setProject] = useState('all');
  const projects = useMemo(() => {
    const s = new Set<string>();
    for (const c of DATA) for (const l of c.links) s.add(l.otherProject);
    return Array.from(s).sort();
  }, []);
  const filtered = useMemo(() => {
    if (project === 'all') return DATA;
    return DATA
      .map((c) => ({ ...c, links: c.links.filter((l) => l.otherProject === project) }))
      .filter((c) => c.links.length > 0);
  }, [project]);

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', padding: 16 }}>
      <h2 style={{ marginTop: 0 }}>Cross-project bridge</h2>
      <div style={{ marginBottom: 12 }}>
        Other project:{' '}
        <select value={project} onChange={(e) => setProject(e.target.value)}>
          <option value="all">all ({projects.length})</option>
          {projects.map((p) => <option key={p} value={p}>{p}</option>)}
        </select>
      </div>
      {filtered.length === 0 && (
        <div style={{ opacity: 0.6 }}>
          No cross-project links. Register more projects with <code>subnet init</code> and run <code>subnet link</code>.
        </div>
      )}
      <div style={{ display: 'grid', gap: 16 }}>
        {filtered.map((c) => (
          <div key={c.id} style={{ border: '1px solid #2a2a2a', borderRadius: 6, padding: 12 }}>
            <div style={{ fontWeight: 600, fontSize: 16 }}>{c.name}</div>
            {c.summary && <div style={{ opacity: 0.85 }}>{c.summary}</div>}
            <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: 10 }}>
              <thead>
                <tr style={{ textAlign: 'left', fontSize: 12, opacity: 0.6 }}>
                  <th>relation</th><th>score</th><th>other project</th><th>other concept</th>
                </tr>
              </thead>
              <tbody>
                {c.links.map((l, i) => (
                  <tr key={i} style={{ borderTop: '1px solid #1a1a1a' }}>
                    <td><span style={{ color: REL_COLORS[l.relation] ?? '#aaa' }}>{l.relation}</span></td>
                    <td>{l.score.toFixed(2)}</td>
                    <td>{l.otherProject}</td>
                    <td>
                      <div>{l.otherName}</div>
                      {l.otherSummary && <div style={{ opacity: 0.7, fontSize: 12 }}>{l.otherSummary}</div>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ))}
      </div>
    </div>
  );
}
