/**
 * decision-timeline.canvas.tsx — generated by `subnet canvas decision-timeline`.
 *
 * Chronological view of decision-like facts (decision / constraint / pattern /
 * business_rule) with their session context and file changes.
 */
import React, { useMemo, useState } from 'react';

interface Entry {
  id: string;
  kind: string;
  title: string;
  summary?: string;
  confidence: number;
  source: string;
  ts: number;
  sessionId?: string;
  files: string[];
}

const DATA: Entry[] = (globalThis as any).__SUBNET_TIMELINE_DATA__ ?? [];

const KIND_COLORS: Record<string, string> = {
  decision: '#5ea0ef',
  business_rule: '#c98be0',
  constraint: '#e8a04e',
  pattern: '#5dd39e',
  problem: '#e0656e',
  solution: '#5dd39e',
  intent: '#9aa0a6',
};

export default function DecisionTimelineCanvas() {
  const [filter, setFilter] = useState('all');
  const kinds = useMemo(() => Array.from(new Set(DATA.map((d) => d.kind))).sort(), []);
  const entries = useMemo(() => {
    const filtered = filter === 'all' ? DATA : DATA.filter((d) => d.kind === filter);
    return [...filtered].sort((a, b) => a.ts - b.ts);
  }, [filter]);

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', padding: 16 }}>
      <h2 style={{ marginTop: 0 }}>Decision timeline</h2>
      <div style={{ marginBottom: 12 }}>
        <label>
          Kind:{' '}
          <select value={filter} onChange={(e) => setFilter(e.target.value)}>
            <option value="all">all</option>
            {kinds.map((k) => (
              <option key={k} value={k}>{k}</option>
            ))}
          </select>
        </label>
        <span style={{ marginLeft: 12, opacity: 0.6 }}>{entries.length} entries</span>
      </div>

      <div style={{ position: 'relative', paddingLeft: 18 }}>
        <div style={{
          position: 'absolute', left: 6, top: 0, bottom: 0, width: 2,
          background: '#2a2a2a',
        }} />
        {entries.map((e) => (
          <div key={e.id} style={{ position: 'relative', marginBottom: 16 }}>
            <div style={{
              position: 'absolute', left: -16, top: 6, width: 10, height: 10, borderRadius: 5,
              background: KIND_COLORS[e.kind] ?? '#888',
            }} />
            <div style={{ fontSize: 12, opacity: 0.6 }}>
              {new Date(e.ts).toLocaleString()} · <span style={{ color: KIND_COLORS[e.kind] ?? '#888' }}>{e.kind}</span> · conf {e.confidence.toFixed(2)}
            </div>
            <div style={{ fontWeight: 600 }}>{e.title}</div>
            {e.summary && <div style={{ opacity: 0.85 }}>{e.summary}</div>}
            {e.files.length > 0 && (
              <div style={{ marginTop: 4, fontFamily: 'ui-monospace, monospace', fontSize: 12, opacity: 0.7 }}>
                files: {e.files.slice(0, 6).join(', ')}
                {e.files.length > 6 ? ` (+${e.files.length - 6})` : ''}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
