/**
 * project-map.canvas.tsx — generated by `subnet canvas project-map`.
 *
 * Shows L3 concepts with their member facts and the L0 code symbols they
 * touch. Filterable by domain and by member count.
 */
import React, { useMemo, useState } from 'react';

interface CodeLink {
  file: string;
  name: string;
  kind: string;
  line: number;
}

interface Member {
  id: string;
  kind: string;
  title: string;
  summary?: string;
  codeLinks: CodeLink[];
}

interface Concept {
  id: string;
  name: string;
  summary?: string;
  domain?: string;
  members: Member[];
}

const DATA: Concept[] = (globalThis as any).__SUBNET_CONCEPTS_DATA__ ?? [];

export default function ProjectMapCanvas() {
  const [domain, setDomain] = useState<string>('all');
  const [minMembers, setMinMembers] = useState(1);
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});

  const domains = useMemo(
    () => Array.from(new Set(DATA.map((c) => c.domain).filter(Boolean))).sort() as string[],
    [],
  );

  const concepts = useMemo(
    () =>
      DATA.filter((c) => (domain === 'all' || c.domain === domain) && c.members.length >= minMembers)
        .sort((a, b) => b.members.length - a.members.length),
    [domain, minMembers],
  );

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', padding: 16 }}>
      <h2 style={{ marginTop: 0 }}>Project knowledge map</h2>

      <div style={{ display: 'flex', gap: 12, marginBottom: 12, alignItems: 'center' }}>
        <label>
          Domain:{' '}
          <select value={domain} onChange={(e) => setDomain(e.target.value)}>
            <option value="all">all</option>
            {domains.map((d) => (
              <option key={d} value={d}>{d}</option>
            ))}
          </select>
        </label>
        <label>
          Min members:{' '}
          <input
            type="number"
            min={1}
            value={minMembers}
            onChange={(e) => setMinMembers(Math.max(1, parseInt(e.target.value, 10) || 1))}
            style={{ width: 60 }}
          />
        </label>
        <span style={{ opacity: 0.7 }}>
          {concepts.length} of {DATA.length} concepts
        </span>
      </div>

      {concepts.length === 0 && (
        <div style={{ opacity: 0.6, padding: 24 }}>
          No concepts yet. Run <code>subnet ingest</code> to populate the knowledge graph.
        </div>
      )}

      <div style={{ display: 'grid', gap: 12 }}>
        {concepts.map((c) => {
          const open = !!expanded[c.id];
          const allLinks = c.members.flatMap((m) => m.codeLinks);
          return (
            <div key={c.id} style={{
              border: '1px solid #2a2a2a', borderRadius: 6, padding: 12,
            }}>
              <div
                onClick={() => setExpanded((p) => ({ ...p, [c.id]: !open }))}
                style={{ display: 'flex', cursor: 'pointer', alignItems: 'baseline', gap: 10 }}
              >
                <div style={{ fontWeight: 600, fontSize: 16 }}>{c.name}</div>
                <div style={{ fontSize: 12, opacity: 0.65 }}>
                  {c.members.length} fact{c.members.length === 1 ? '' : 's'}
                  {allLinks.length ? ` · ${allLinks.length} code link${allLinks.length === 1 ? '' : 's'}` : ''}
                  {c.domain ? ` · ${c.domain}` : ''}
                </div>
                <div style={{ marginLeft: 'auto', opacity: 0.6 }}>{open ? '▾' : '▸'}</div>
              </div>
              {c.summary && (
                <div style={{ opacity: 0.85, marginTop: 6 }}>{c.summary}</div>
              )}
              {open && (
                <div style={{ marginTop: 10 }}>
                  <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                    <thead>
                      <tr style={{ textAlign: 'left', fontSize: 12, opacity: 0.6, borderBottom: '1px solid #2a2a2a' }}>
                        <th>kind</th><th>title / summary</th><th>code</th>
                      </tr>
                    </thead>
                    <tbody>
                      {c.members.map((m) => (
                        <tr key={m.id} style={{ verticalAlign: 'top', borderBottom: '1px solid #1a1a1a' }}>
                          <td style={{ padding: '6px 8px 6px 0' }}>{m.kind}</td>
                          <td style={{ padding: '6px 8px 6px 0' }}>
                            <div style={{ fontWeight: 500 }}>{m.title}</div>
                            {m.summary && <div style={{ opacity: 0.75, fontSize: 13 }}>{m.summary}</div>}
                          </td>
                          <td style={{ padding: '6px 0', fontFamily: 'ui-monospace, monospace', fontSize: 12 }}>
                            {m.codeLinks.length === 0
                              ? <span style={{ opacity: 0.4 }}>—</span>
                              : m.codeLinks.slice(0, 4).map((l, i) => (
                                  <div key={i}>{l.file}:{l.line}</div>
                                ))
                            }
                            {m.codeLinks.length > 4 && (
                              <div style={{ opacity: 0.5 }}>+{m.codeLinks.length - 4} more</div>
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
