/**
 * triage-audit.canvas.tsx — generated by `subnet canvas triage-audit`.
 *
 * Shows every triaged window: labels, rationale, kept/dropped status. Lets
 * the user filter and inspect the agent's classification calls.
 *
 * This file is a runtime artifact. Edit the template at
 * src/canvas/templates/triage-audit.canvas.tsx, then re-generate.
 *
 * Data source: the generator reads .substrate-net/knowledge.db at write time and
 * inlines a JSON snapshot. The canvas is therefore self-contained and offline.
 */
import React, { useMemo, useState } from 'react';

interface Row {
  windowId: string;
  sessionId: string;
  domain: string;
  relevance: string;
  quality: string;
  linkage: string;
  confidence: number;
  kept: boolean;
  rationale: string;
  excerpt: string;
}

// __DATA__ is replaced by the canvas generator at write time.
const DATA: Row[] = (globalThis as any).__SUBNET_TRIAGE_DATA__ ?? [];

export default function TriageAuditCanvas() {
  const [filter, setFilter] = useState<'all' | 'kept' | 'dropped'>('all');
  const [domain, setDomain] = useState<string>('all');

  const rows = useMemo(
    () =>
      DATA.filter((r) => {
        if (filter === 'kept' && !r.kept) return false;
        if (filter === 'dropped' && r.kept) return false;
        if (domain !== 'all' && r.domain !== domain) return false;
        return true;
      }),
    [filter, domain],
  );

  const domains = useMemo(() => Array.from(new Set(DATA.map((r) => r.domain))).sort(), []);

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', padding: 16 }}>
      <h2 style={{ marginTop: 0 }}>Triage audit</h2>
      <div style={{ display: 'flex', gap: 12, marginBottom: 12 }}>
        <select value={filter} onChange={(e) => setFilter(e.target.value as any)}>
          <option value="all">all ({DATA.length})</option>
          <option value="kept">kept ({DATA.filter((r) => r.kept).length})</option>
          <option value="dropped">dropped ({DATA.filter((r) => !r.kept).length})</option>
        </select>
        <select value={domain} onChange={(e) => setDomain(e.target.value)}>
          <option value="all">domain: all</option>
          {domains.map((d) => (
            <option key={d} value={d}>
              domain: {d}
            </option>
          ))}
        </select>
        <span style={{ alignSelf: 'center', opacity: 0.6 }}>
          showing {rows.length} of {DATA.length}
        </span>
      </div>
      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <thead>
          <tr style={{ textAlign: 'left', borderBottom: '1px solid #888' }}>
            <th>domain</th><th>quality</th><th>relevance</th><th>linkage</th>
            <th>conf</th><th>kept</th><th>rationale</th><th>excerpt</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.windowId} style={{ borderBottom: '1px solid #2a2a2a' }}>
              <td>{r.domain}</td>
              <td>{r.quality}</td>
              <td>{r.relevance}</td>
              <td>{r.linkage}</td>
              <td>{r.confidence.toFixed(2)}</td>
              <td style={{ color: r.kept ? '#5d5' : '#d55' }}>{r.kept ? 'kept' : 'dropped'}</td>
              <td style={{ maxWidth: 280 }}>{r.rationale}</td>
              <td style={{ maxWidth: 360, whiteSpace: 'pre-wrap', fontFamily: 'ui-monospace, monospace', fontSize: 12, opacity: 0.7 }}>
                {r.excerpt}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
